 trail_id |         trail_name         |                             trail_image                              |                            trail_google_direction                             |                                                                                           trail_yelp_link                                                                                           
----------+----------------------------+----------------------------------------------------------------------+-------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        1 | Mount Tamalpais State Park | https://s3-media2.fl.yelpcdn.com/bphoto/Vpt9-Neegbdsu_-d0W5xDg/o.jpg | https://www.google.com/maps/dir//3801+Panoramic+Hwy%0AMill+Valley%2C+CA+94941 | https://www.yelp.com/biz/mount-tamalpais-state-park-mill-valley?adjust_creative=5DAtUGW4yblYDIizdvHtsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5DAtUGW4yblYDIizdvHtsA
        2 | Alameda Creek Trails       | https://s3-media1.fl.yelpcdn.com/bphoto/kGwmEkUgUQM7M69qbEd9YQ/o.jpg | https://www.google.com/maps/dir//2250+Isherwood+Way%0AFremont%2C+CA+94536     | https://www.yelp.com/biz/alameda-creek-trails-fremont?adjust_creative=5DAtUGW4yblYDIizdvHtsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5DAtUGW4yblYDIizdvHtsA
        3 | Mount Tamalpais State Park | https://s3-media2.fl.yelpcdn.com/bphoto/Vpt9-Neegbdsu_-d0W5xDg/o.jpg | https://www.google.com/maps/dir//3801+Panoramic+Hwy%0AMill+Valley%2C+CA+94941 | https://www.yelp.com/biz/mount-tamalpais-state-park-mill-valley?adjust_creative=5DAtUGW4yblYDIizdvHtsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5DAtUGW4yblYDIizdvHtsA
        4 | Tiburon Ridge Trail        | https://s3-media1.fl.yelpcdn.com/bphoto/7B14JmPmVTTCKcrC1goo2w/o.jpg | https://www.google.com/maps/dir//End+Of+Lyford+Dr%0ATiburon%2C+CA+94920       | https://www.yelp.com/biz/tiburon-ridge-trail-tiburon?adjust_creative=5DAtUGW4yblYDIizdvHtsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5DAtUGW4yblYDIizdvHtsA
        5 | Tiburon Ridge Trail        | https://s3-media1.fl.yelpcdn.com/bphoto/7B14JmPmVTTCKcrC1goo2w/o.jpg | https://www.google.com/maps/dir//End+Of+Lyford+Dr%0ATiburon%2C+CA+94920       | https://www.yelp.com/biz/tiburon-ridge-trail-tiburon?adjust_creative=5DAtUGW4yblYDIizdvHtsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5DAtUGW4yblYDIizdvHtsA
        6 | Mount Tamalpais State Park | https://s3-media2.fl.yelpcdn.com/bphoto/Vpt9-Neegbdsu_-d0W5xDg/o.jpg | https://www.google.com/maps/dir//3801+Panoramic+Hwy%0AMill+Valley%2C+CA+94941 | https://www.yelp.com/biz/mount-tamalpais-state-park-mill-valley?adjust_creative=5DAtUGW4yblYDIizdvHtsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5DAtUGW4yblYDIizdvHtsA
        7 | Tiburon Ridge Trail        | https://s3-media1.fl.yelpcdn.com/bphoto/7B14JmPmVTTCKcrC1goo2w/o.jpg | https://www.google.com/maps/dir//End+Of+Lyford+Dr%0ATiburon%2C+CA+94920       | https://www.yelp.com/biz/tiburon-ridge-trail-tiburon?adjust_creative=5DAtUGW4yblYDIizdvHtsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5DAtUGW4yblYDIizdvHtsA
        8 | Mount Tamalpais State Park | https://s3-media2.fl.yelpcdn.com/bphoto/Vpt9-Neegbdsu_-d0W5xDg/o.jpg | https://www.google.com/maps/dir//3801+Panoramic+Hwy%0AMill+Valley%2C+CA+94941 | https://www.yelp.com/biz/mount-tamalpais-state-park-mill-valley?adjust_creative=5DAtUGW4yblYDIizdvHtsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5DAtUGW4yblYDIizdvHtsA
        9 | Tiburon Ridge Trail        | https://s3-media1.fl.yelpcdn.com/bphoto/7B14JmPmVTTCKcrC1goo2w/o.jpg | https://www.google.com/maps/dir//End+Of+Lyford+Dr%0ATiburon%2C+CA+94920       | https://www.yelp.com/biz/tiburon-ridge-trail-tiburon?adjust_creative=5DAtUGW4yblYDIizdvHtsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5DAtUGW4yblYDIizdvHtsA
(9 rows)

